//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LinDataFrame.msg.
//

#ifndef __LINDATAFRAME_M_H
#define __LINDATAFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class LinBreakSignal;
class LinHeader;
class LinResponse;
// cplusplus {{
#include <omnetpp.h>
// }}

/**
 * Class generated from <tt>LinDataFrame.msg:6</tt> by opp_msgtool.
 * <pre>
 * // 1) The Break field is a physical signal (dominant state), not a data byte.
 * packet LinBreakSignal
 * {
 *     // True node identity (set by sender LinNode::nodeAddress)
 *     int sourceAddr = -1;
 * 
 *     // Bus ingress information (set by LinBusLogic from arrival gate index)
 *     int ingressPortIndex = -1;
 * 
 *     double duration; // Duration of the dominant state (min 13 bit times)
 * }
 * </pre>
 */
class LinBreakSignal : public ::omnetpp::cPacket
{
  protected:
    int sourceAddr = -1;
    int ingressPortIndex = -1;
    double duration = 0;

  private:
    void copy(const LinBreakSignal& other);

  protected:
    bool operator==(const LinBreakSignal&) = delete;

  public:
    LinBreakSignal(const char *name=nullptr, short kind=0);
    LinBreakSignal(const LinBreakSignal& other);
    virtual ~LinBreakSignal();
    LinBreakSignal& operator=(const LinBreakSignal& other);
    virtual LinBreakSignal *dup() const override {return new LinBreakSignal(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceAddr() const;
    virtual void setSourceAddr(int sourceAddr);

    virtual int getIngressPortIndex() const;
    virtual void setIngressPortIndex(int ingressPortIndex);

    virtual double getDuration() const;
    virtual void setDuration(double duration);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LinBreakSignal& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LinBreakSignal& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>LinDataFrame.msg:17</tt> by opp_msgtool.
 * <pre>
 * // 2) The Header remainder (Sync + PID) sent by the Master
 * packet LinHeader
 * {
 *     int sourceAddr = -1;         // True node identity (sender nodeAddress)
 *     int ingressPortIndex = -1;   // Bus port index where it entered
 * 
 *     int frameId;      // Useful for simulation logic (metadata)
 *     int pid;          // Protected Identifier (6-bit ID + 2 parity bits)
 *     char syncByte = 0x55;
 * }
 * </pre>
 */
class LinHeader : public ::omnetpp::cPacket
{
  protected:
    int sourceAddr = -1;
    int ingressPortIndex = -1;
    int frameId = 0;
    int pid = 0;
    char syncByte = 0x55;

  private:
    void copy(const LinHeader& other);

  protected:
    bool operator==(const LinHeader&) = delete;

  public:
    LinHeader(const char *name=nullptr, short kind=0);
    LinHeader(const LinHeader& other);
    virtual ~LinHeader();
    LinHeader& operator=(const LinHeader& other);
    virtual LinHeader *dup() const override {return new LinHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceAddr() const;
    virtual void setSourceAddr(int sourceAddr);

    virtual int getIngressPortIndex() const;
    virtual void setIngressPortIndex(int ingressPortIndex);

    virtual int getFrameId() const;
    virtual void setFrameId(int frameId);

    virtual int getPid() const;
    virtual void setPid(int pid);

    virtual char getSyncByte() const;
    virtual void setSyncByte(char syncByte);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LinHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LinHeader& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>LinDataFrame.msg:27</tt> by opp_msgtool.
 * <pre>
 * // 3) The Response part (Data + Checksum) sent by Publisher (Master or Slave)
 * packet LinResponse
 * {
 *     int sourceAddr = -1;         // True node identity (sender nodeAddress)
 *     int ingressPortIndex = -1;   // Bus port index where it entered
 * 
 *     int frameId;      // Metadata to help receivers match response to header
 *     int dataLength = 8;
 *     char data[8];
 *     char checksum;    // Classic or Enhanced checksum
 * 
 *     // Flag to indicate this response collided on the bus
 *     bool collision = false;
 * }
 * </pre>
 */
class LinResponse : public ::omnetpp::cPacket
{
  protected:
    int sourceAddr = -1;
    int ingressPortIndex = -1;
    int frameId = 0;
    int dataLength = 8;
    char data[8] = {0};
    char checksum = 0;
    bool collision = false;

  private:
    void copy(const LinResponse& other);

  protected:
    bool operator==(const LinResponse&) = delete;

  public:
    LinResponse(const char *name=nullptr, short kind=0);
    LinResponse(const LinResponse& other);
    virtual ~LinResponse();
    LinResponse& operator=(const LinResponse& other);
    virtual LinResponse *dup() const override {return new LinResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceAddr() const;
    virtual void setSourceAddr(int sourceAddr);

    virtual int getIngressPortIndex() const;
    virtual void setIngressPortIndex(int ingressPortIndex);

    virtual int getFrameId() const;
    virtual void setFrameId(int frameId);

    virtual int getDataLength() const;
    virtual void setDataLength(int dataLength);

    virtual size_t getDataArraySize() const;
    virtual char getData(size_t k) const;
    virtual void setData(size_t k, char data);

    virtual char getChecksum() const;
    virtual void setChecksum(char checksum);

    virtual bool getCollision() const;
    virtual void setCollision(bool collision);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LinResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LinResponse& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline LinBreakSignal *fromAnyPtr(any_ptr ptr) { return check_and_cast<LinBreakSignal*>(ptr.get<cObject>()); }
template<> inline LinHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<LinHeader*>(ptr.get<cObject>()); }
template<> inline LinResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<LinResponse*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __LINDATAFRAME_M_H

